### ISSUE TITLE
Unable to tunnel into the HPE matrix (proxy.houston.hpecorp.net proxy.houston.hpecorp.net)

### ISSUE THREAD

**Issue by peytonmcnully** [HewlettPackard/hpe-oneview-hubot#79] opened 2017-05-15 23:36 UTC
```[Mon May 15 2017 23:18:17 GMT+0000 (UTC)] INFO hubot-redis-brain: Using default redis on localhost:6379
Unhandled rejection RequestError: Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy.houston.hpecorp.net proxy.houston.hpecorp.net:8088
  at new RequestError (/home/docker/hubot/node_modules/request-promise-core/lib/errors.js:14:15)
  at Request.plumbing.callback (/home/docker/hubot/node_modules/request-promise-core/lib/plumbing.js:87:29)
  at Request.RP$callback [as _callback] (/home/docker/hubot/node_modules/request-promise-core/lib/plumbing.js:46:31)
  at self.callback (/home/docker/hubot/node_modules/request/request.js:186:22)
  at emitOne (events.js:96:13)
  at Request.emit (events.js:188:7)
  at Request.onRequestError (/home/docker/hubot/node_modules/request/request.js:845:8)
  at emitOne (events.js:96:13)
  at ClientRequest.emit (events.js:188:7)
  at ClientRequest.onError (/home/docker/hubot/node_modules/tunnel-agent/index.js:178:21)
  at ClientRequest.g (events.js:291:16)
  at emitOne (events.js:96:13)
  at ClientRequest.emit (events.js:188:7)
  at Socket.socketErrorListener (_http_client.js:310:9)
  at emitOne (events.js:96:13)
  at Socket.emit (events.js:188:7)
  at connectErrorNT (net.js:1022:8)
  at _combinedTickCallback (internal/process/next_tick.js:74:11)
  at process._tickCallback (internal/process/next_tick.js:98:9)  ```

**Comment by danielreed** [comment] 2017-05-16 15:04
We just merged a fix for this. Would you let us know if it resolves your issue?

**Comment by peytonmcnully** [comment] 2017-05-16 18:31
hey @danielreed fixed first instance of the issue. Looks like redis is still trapped in the matrix.

```Unhandled rejection RequestError: Error: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND proxy.houston.hpecorp.net proxy.houston.hpecorp.net:8088```

**Comment by danielreed** [comment] 2017-05-16 19:56
Do you see these entries in the hubot log:

_INFO Connecting to SCMB
INFO Logged into OV appliance.
INFO Connected to SCMB, waiting for messages_

I'm wondering if now the issue is connecting to the OV SCMB through the proxy.

**Comment by jasonpropp** [comment] 2017-05-16 20:46
@peytonmcnully Also, were you inside the HPE network when you encountered this?  That proxy you're using wouldn't be accessible outside the internal network, and that error looks like a general failure to connect as I'd expect if you couldn't access the proxy.

**Comment by peytonmcnully** [comment] 2017-05-17 03:04
@jasonpropp well outside of the HPE network. In [dockerfile-core](https://github.com/HewlettPackard/hpe-oneview-hubot/blame/master/Dockerfile-core#L25-L29)
> ARG PROXY
> ENV http_proxy http://$PROXY
> ENV https_proxy http://$PROXY
> ENV HTTP_PROXY http://$PROXY
> ENV HTTPS_PROXY http://$PROXY  

is setting the proxy and [docker_run.sh](https://github.com/HewlettPackard/hpe-oneview-hubot/blob/master/docker_run.sh#L42) noproxy= appears to be ignored... Just a guess tho.

**Comment by jesseolsen** [comment] 2017-05-18 15:32
@peytonmcnully Can you paste the output from running "set" from the commandline?
Also, I'm wondering where you got "proxy.houston.hpecorp.net" from.  The documentation _used_ to say to set your PROXY to this value, but has since been updated and says to use your own proxy, if needed.  Here is the updated documentation:
https://github.com/HewlettPackard/hpe-oneview-hubot/wiki/Getting-Started

Also, you need to have your own oneView instance that you point to.  Is this what you are expecting, or were you wanting to use an instance owned by HPE?  I ask because of the title of this issue ("Unable to tunnel into the HPE matrix ").  This title sounds like you might be thinking that you should be connecting to an HPE OneView instance, but in fact you would need to point to your own OneView instance.

I hope this helps.

**Comment by jasonpropp** [comment] 2017-06-02 21:19
@peytonmcnully Did you resolve this issue?  Is it alright to close it?

**Closed** 2017-06-08 19:30 UTC
